// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Attribute, AttributeData, AttributeTableId } from "./tables/Attribute.sol";
import { Skill, SkillData, SkillTableId } from "./tables/Skill.sol";
import { Buff, BuffData, BuffTableId } from "./tables/Buff.sol";
import { Synthesis, SynthesisData, SynthesisTableId } from "./tables/Synthesis.sol";
import { Hero, HeroData, HeroTableId } from "./tables/Hero.sol";
import { Race, RaceTableId } from "./tables/Race.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
