// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IHeroSystem {
  function requestRandomWords() external returns (uint256 requestId);

  function getRequestStatus(uint256 _requestId) external view returns (bool fulfilled, uint256[] memory randomWords);

  function getHero() external returns (uint32);
}
